### ISSUE TITLE
Folders part very slow

### ISSUE THREAD

**Issue by SrSelse** [syncthing/tech-ui#12]
Hello,

I am trying this out after being recommended from the syncthing forum that this will work better for large scale systems like we have currently.

However, I seem to have an issue with it currently. The device-part is super-quick and gives me all the devices within a second or two. The folder part however takes like forever to get any data from. The first folder shows after about 3 minutes and then there's another 3 minutes before the next folder shows up. 

I am also checking with API-calls at the same time and it seems like the calls to /rest/db/status?folder=XXX is the issue that takes the most time. The API-calls to /rest/db/completion?device= is quick, as well as the calls to /rest/db/completion?folder=XX.

Is there some way to tweak the API-calls for this UI to use the /rest/db/completion instead of the /rest/db/status? Or do they not show the same information needed to get the UI complete?

**Comment by calmh** [comment]
The /db/status call should be pretty much instantaneous, it mostly returns stuff already pre-calculated in RAM. I think you have other more serious issues with the setup not related to the GUI. Unless you are running an old version of Syncthing (pre 1.6.0).
